import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ToastContainer } from "react-toastify";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        {/* <header className="bg-black text-white p-3 text-center text-2xl">
          Job Tracker
        </header> */}
        <Sidebar />
        <div className="bg-gray-300">{children}</div>

        <footer className="bg-black text-white p-3 w-full text-center fixed bottom-0">
          ©2025, Shreyas Raut
        </footer>
      </body>
    </html>
  );
}
